M48
; DRILL file {KiCad (6.0.7-1)-1} date Wednesday, January 25, 2023 at 04:43:49 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-01-25T16:43:49-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7-1)-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1063
%
G90
G05
T1
X3.4646Y-2.2844
X3.4646Y-3.2283
X5.1969Y-2.2835
X5.1969Y-3.2283
T0
M30
