M48
; DRILL file {KiCad 7.0.10} date Sat 10 Feb 2024 08:18:09 PM CST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-02-10T20:18:09-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0984
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1083
%
G90
G05
T1
X1.235Y-3.495
X1.85Y-6.73
X3.835Y-4.08
X4.46Y-7.45
T2
X1.6283Y-2.5045
X1.6283Y-3.41
X3.9117Y-2.5045
X3.9117Y-3.41
M30
